'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace FoodServiceRef
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Recipe", [Namespace]:="http://schemas.datacontract.org/2004/07/FoodSecretsServices"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Recipe
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private caloriesField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private carbsField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private fatField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private idField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private imageField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private imageTypeField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private proteinField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private titleField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property calories() As String
            Get
                Return Me.caloriesField
            End Get
            Set
                If (Object.ReferenceEquals(Me.caloriesField, value) <> true) Then
                    Me.caloriesField = value
                    Me.RaisePropertyChanged("calories")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property carbs() As String
            Get
                Return Me.carbsField
            End Get
            Set
                If (Object.ReferenceEquals(Me.carbsField, value) <> true) Then
                    Me.carbsField = value
                    Me.RaisePropertyChanged("carbs")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property fat() As String
            Get
                Return Me.fatField
            End Get
            Set
                If (Object.ReferenceEquals(Me.fatField, value) <> true) Then
                    Me.fatField = value
                    Me.RaisePropertyChanged("fat")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property id() As String
            Get
                Return Me.idField
            End Get
            Set
                If (Object.ReferenceEquals(Me.idField, value) <> true) Then
                    Me.idField = value
                    Me.RaisePropertyChanged("id")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property image() As String
            Get
                Return Me.imageField
            End Get
            Set
                If (Object.ReferenceEquals(Me.imageField, value) <> true) Then
                    Me.imageField = value
                    Me.RaisePropertyChanged("image")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property imageType() As String
            Get
                Return Me.imageTypeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.imageTypeField, value) <> true) Then
                    Me.imageTypeField = value
                    Me.RaisePropertyChanged("imageType")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property protein() As String
            Get
                Return Me.proteinField
            End Get
            Set
                If (Object.ReferenceEquals(Me.proteinField, value) <> true) Then
                    Me.proteinField = value
                    Me.RaisePropertyChanged("protein")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property title() As String
            Get
                Return Me.titleField
            End Get
            Set
                If (Object.ReferenceEquals(Me.titleField, value) <> true) Then
                    Me.titleField = value
                    Me.RaisePropertyChanged("title")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="DailyMeals", [Namespace]:="http://schemas.datacontract.org/2004/07/FoodSecretsServices"),  _
     System.SerializableAttribute()>  _
    Partial Public Class DailyMeals
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private caloriesField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private carbohydratesField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private fatField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private mealsField() As FoodServiceRef.Meal
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private proteinField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property calories() As String
            Get
                Return Me.caloriesField
            End Get
            Set
                If (Object.ReferenceEquals(Me.caloriesField, value) <> true) Then
                    Me.caloriesField = value
                    Me.RaisePropertyChanged("calories")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property carbohydrates() As String
            Get
                Return Me.carbohydratesField
            End Get
            Set
                If (Object.ReferenceEquals(Me.carbohydratesField, value) <> true) Then
                    Me.carbohydratesField = value
                    Me.RaisePropertyChanged("carbohydrates")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property fat() As String
            Get
                Return Me.fatField
            End Get
            Set
                If (Object.ReferenceEquals(Me.fatField, value) <> true) Then
                    Me.fatField = value
                    Me.RaisePropertyChanged("fat")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property meals() As FoodServiceRef.Meal()
            Get
                Return Me.mealsField
            End Get
            Set
                If (Object.ReferenceEquals(Me.mealsField, value) <> true) Then
                    Me.mealsField = value
                    Me.RaisePropertyChanged("meals")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property protein() As String
            Get
                Return Me.proteinField
            End Get
            Set
                If (Object.ReferenceEquals(Me.proteinField, value) <> true) Then
                    Me.proteinField = value
                    Me.RaisePropertyChanged("protein")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Meal", [Namespace]:="http://schemas.datacontract.org/2004/07/FoodSecretsServices"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Meal
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private idField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private imageField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private readyInMinutesField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private titleField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property id() As String
            Get
                Return Me.idField
            End Get
            Set
                If (Object.ReferenceEquals(Me.idField, value) <> true) Then
                    Me.idField = value
                    Me.RaisePropertyChanged("id")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property image() As String
            Get
                Return Me.imageField
            End Get
            Set
                If (Object.ReferenceEquals(Me.imageField, value) <> true) Then
                    Me.imageField = value
                    Me.RaisePropertyChanged("image")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property readyInMinutes() As String
            Get
                Return Me.readyInMinutesField
            End Get
            Set
                If (Object.ReferenceEquals(Me.readyInMinutesField, value) <> true) Then
                    Me.readyInMinutesField = value
                    Me.RaisePropertyChanged("readyInMinutes")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property title() As String
            Get
                Return Me.titleField
            End Get
            Set
                If (Object.ReferenceEquals(Me.titleField, value) <> true) Then
                    Me.titleField = value
                    Me.RaisePropertyChanged("title")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="RecipeInformation", [Namespace]:="http://schemas.datacontract.org/2004/07/FoodSecretsServices"),  _
     System.SerializableAttribute()>  _
    Partial Public Class RecipeInformation
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CaloriesField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CarbsField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FatField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ProteinField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private aggregateLikesField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private cheapField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private imageField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private readyInMinutesField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private servingsField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private spoonacularScoreField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private titleField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private veryHealthyField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private veryPopularField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private weightWatcherSmartPointsField As Integer
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Calories() As Integer
            Get
                Return Me.CaloriesField
            End Get
            Set
                If (Me.CaloriesField.Equals(value) <> true) Then
                    Me.CaloriesField = value
                    Me.RaisePropertyChanged("Calories")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Carbs() As Integer
            Get
                Return Me.CarbsField
            End Get
            Set
                If (Me.CarbsField.Equals(value) <> true) Then
                    Me.CarbsField = value
                    Me.RaisePropertyChanged("Carbs")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Fat() As Integer
            Get
                Return Me.FatField
            End Get
            Set
                If (Me.FatField.Equals(value) <> true) Then
                    Me.FatField = value
                    Me.RaisePropertyChanged("Fat")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Protein() As Integer
            Get
                Return Me.ProteinField
            End Get
            Set
                If (Me.ProteinField.Equals(value) <> true) Then
                    Me.ProteinField = value
                    Me.RaisePropertyChanged("Protein")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property aggregateLikes() As Integer
            Get
                Return Me.aggregateLikesField
            End Get
            Set
                If (Me.aggregateLikesField.Equals(value) <> true) Then
                    Me.aggregateLikesField = value
                    Me.RaisePropertyChanged("aggregateLikes")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property cheap() As Boolean
            Get
                Return Me.cheapField
            End Get
            Set
                If (Me.cheapField.Equals(value) <> true) Then
                    Me.cheapField = value
                    Me.RaisePropertyChanged("cheap")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property image() As String
            Get
                Return Me.imageField
            End Get
            Set
                If (Object.ReferenceEquals(Me.imageField, value) <> true) Then
                    Me.imageField = value
                    Me.RaisePropertyChanged("image")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property readyInMinutes() As Integer
            Get
                Return Me.readyInMinutesField
            End Get
            Set
                If (Me.readyInMinutesField.Equals(value) <> true) Then
                    Me.readyInMinutesField = value
                    Me.RaisePropertyChanged("readyInMinutes")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property servings() As Boolean
            Get
                Return Me.servingsField
            End Get
            Set
                If (Me.servingsField.Equals(value) <> true) Then
                    Me.servingsField = value
                    Me.RaisePropertyChanged("servings")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property spoonacularScore() As Integer
            Get
                Return Me.spoonacularScoreField
            End Get
            Set
                If (Me.spoonacularScoreField.Equals(value) <> true) Then
                    Me.spoonacularScoreField = value
                    Me.RaisePropertyChanged("spoonacularScore")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property title() As String
            Get
                Return Me.titleField
            End Get
            Set
                If (Object.ReferenceEquals(Me.titleField, value) <> true) Then
                    Me.titleField = value
                    Me.RaisePropertyChanged("title")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property veryHealthy() As Boolean
            Get
                Return Me.veryHealthyField
            End Get
            Set
                If (Me.veryHealthyField.Equals(value) <> true) Then
                    Me.veryHealthyField = value
                    Me.RaisePropertyChanged("veryHealthy")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property veryPopular() As Boolean
            Get
                Return Me.veryPopularField
            End Get
            Set
                If (Me.veryPopularField.Equals(value) <> true) Then
                    Me.veryPopularField = value
                    Me.RaisePropertyChanged("veryPopular")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property weightWatcherSmartPoints() As Integer
            Get
                Return Me.weightWatcherSmartPointsField
            End Get
            Set
                If (Me.weightWatcherSmartPointsField.Equals(value) <> true) Then
                    Me.weightWatcherSmartPointsField = value
                    Me.RaisePropertyChanged("weightWatcherSmartPoints")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="FoodServiceRef.IFoodSecretService")>  _
    Public Interface IFoodSecretService
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IFoodSecretService/SearchRecipeByName", ReplyAction:="http://tempuri.org/IFoodSecretService/SearchRecipeByNameResponse")>  _
        Function SearchRecipeByName(ByVal RecipeName As String) As FoodServiceRef.Recipe()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IFoodSecretService/SearchRecipeByName", ReplyAction:="http://tempuri.org/IFoodSecretService/SearchRecipeByNameResponse")>  _
        Function SearchRecipeByNameAsync(ByVal RecipeName As String) As System.Threading.Tasks.Task(Of FoodServiceRef.Recipe())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IFoodSecretService/SearchRecipeByIngredients", ReplyAction:="http://tempuri.org/IFoodSecretService/SearchRecipeByIngredientsResponse")>  _
        Function SearchRecipeByIngredients(ByVal ingredients As String) As FoodServiceRef.Recipe()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IFoodSecretService/SearchRecipeByIngredients", ReplyAction:="http://tempuri.org/IFoodSecretService/SearchRecipeByIngredientsResponse")>  _
        Function SearchRecipeByIngredientsAsync(ByVal ingredients As String) As System.Threading.Tasks.Task(Of FoodServiceRef.Recipe())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IFoodSecretService/SearchRecipeByNutrients", ReplyAction:="http://tempuri.org/IFoodSecretService/SearchRecipeByNutrientsResponse")>  _
        Function SearchRecipeByNutrients(ByVal maxcalories As Integer, ByVal maxcarbs As Integer, ByVal maxfat As Integer, ByVal maxprotein As Integer) As FoodServiceRef.Recipe()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IFoodSecretService/SearchRecipeByNutrients", ReplyAction:="http://tempuri.org/IFoodSecretService/SearchRecipeByNutrientsResponse")>  _
        Function SearchRecipeByNutrientsAsync(ByVal maxcalories As Integer, ByVal maxcarbs As Integer, ByVal maxfat As Integer, ByVal maxprotein As Integer) As System.Threading.Tasks.Task(Of FoodServiceRef.Recipe())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IFoodSecretService/MatchRecipesDailyCalories", ReplyAction:="http://tempuri.org/IFoodSecretService/MatchRecipesDailyCaloriesResponse")>  _
        Function MatchRecipesDailyCalories(ByVal targetCalories As Integer) As FoodServiceRef.DailyMeals
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IFoodSecretService/MatchRecipesDailyCalories", ReplyAction:="http://tempuri.org/IFoodSecretService/MatchRecipesDailyCaloriesResponse")>  _
        Function MatchRecipesDailyCaloriesAsync(ByVal targetCalories As Integer) As System.Threading.Tasks.Task(Of FoodServiceRef.DailyMeals)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IFoodSecretService/GetRecipeInformation", ReplyAction:="http://tempuri.org/IFoodSecretService/GetRecipeInformationResponse")>  _
        Function GetRecipeInformation(ByVal RecipeID As Integer) As FoodServiceRef.RecipeInformation
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IFoodSecretService/GetRecipeInformation", ReplyAction:="http://tempuri.org/IFoodSecretService/GetRecipeInformationResponse")>  _
        Function GetRecipeInformationAsync(ByVal RecipeID As Integer) As System.Threading.Tasks.Task(Of FoodServiceRef.RecipeInformation)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IFoodSecretServiceChannel
        Inherits FoodServiceRef.IFoodSecretService, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class FoodSecretServiceClient
        Inherits System.ServiceModel.ClientBase(Of FoodServiceRef.IFoodSecretService)
        Implements FoodServiceRef.IFoodSecretService
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function SearchRecipeByName(ByVal RecipeName As String) As FoodServiceRef.Recipe() Implements FoodServiceRef.IFoodSecretService.SearchRecipeByName
            Return MyBase.Channel.SearchRecipeByName(RecipeName)
        End Function
        
        Public Function SearchRecipeByNameAsync(ByVal RecipeName As String) As System.Threading.Tasks.Task(Of FoodServiceRef.Recipe()) Implements FoodServiceRef.IFoodSecretService.SearchRecipeByNameAsync
            Return MyBase.Channel.SearchRecipeByNameAsync(RecipeName)
        End Function
        
        Public Function SearchRecipeByIngredients(ByVal ingredients As String) As FoodServiceRef.Recipe() Implements FoodServiceRef.IFoodSecretService.SearchRecipeByIngredients
            Return MyBase.Channel.SearchRecipeByIngredients(ingredients)
        End Function
        
        Public Function SearchRecipeByIngredientsAsync(ByVal ingredients As String) As System.Threading.Tasks.Task(Of FoodServiceRef.Recipe()) Implements FoodServiceRef.IFoodSecretService.SearchRecipeByIngredientsAsync
            Return MyBase.Channel.SearchRecipeByIngredientsAsync(ingredients)
        End Function
        
        Public Function SearchRecipeByNutrients(ByVal maxcalories As Integer, ByVal maxcarbs As Integer, ByVal maxfat As Integer, ByVal maxprotein As Integer) As FoodServiceRef.Recipe() Implements FoodServiceRef.IFoodSecretService.SearchRecipeByNutrients
            Return MyBase.Channel.SearchRecipeByNutrients(maxcalories, maxcarbs, maxfat, maxprotein)
        End Function
        
        Public Function SearchRecipeByNutrientsAsync(ByVal maxcalories As Integer, ByVal maxcarbs As Integer, ByVal maxfat As Integer, ByVal maxprotein As Integer) As System.Threading.Tasks.Task(Of FoodServiceRef.Recipe()) Implements FoodServiceRef.IFoodSecretService.SearchRecipeByNutrientsAsync
            Return MyBase.Channel.SearchRecipeByNutrientsAsync(maxcalories, maxcarbs, maxfat, maxprotein)
        End Function
        
        Public Function MatchRecipesDailyCalories(ByVal targetCalories As Integer) As FoodServiceRef.DailyMeals Implements FoodServiceRef.IFoodSecretService.MatchRecipesDailyCalories
            Return MyBase.Channel.MatchRecipesDailyCalories(targetCalories)
        End Function
        
        Public Function MatchRecipesDailyCaloriesAsync(ByVal targetCalories As Integer) As System.Threading.Tasks.Task(Of FoodServiceRef.DailyMeals) Implements FoodServiceRef.IFoodSecretService.MatchRecipesDailyCaloriesAsync
            Return MyBase.Channel.MatchRecipesDailyCaloriesAsync(targetCalories)
        End Function
        
        Public Function GetRecipeInformation(ByVal RecipeID As Integer) As FoodServiceRef.RecipeInformation Implements FoodServiceRef.IFoodSecretService.GetRecipeInformation
            Return MyBase.Channel.GetRecipeInformation(RecipeID)
        End Function
        
        Public Function GetRecipeInformationAsync(ByVal RecipeID As Integer) As System.Threading.Tasks.Task(Of FoodServiceRef.RecipeInformation) Implements FoodServiceRef.IFoodSecretService.GetRecipeInformationAsync
            Return MyBase.Channel.GetRecipeInformationAsync(RecipeID)
        End Function
    End Class
End Namespace
